POST http://localhost:3000/api/users
Content-Type: application/json

{
      "nombre": "Omar",
      "apellido": "Soto",
      "password": "elOmi",
      "expediente": "711111",
      "carrera": "Ingeniería en Sistemas Computacionales",
      "email": "ie711111@iteso.mx"
}

###

POST http://localhost:3000/api/users
Content-Type: application/json

{
      "nombre": "Anahí",
      "apellido": "Santana",
      "password": "aSantana",
      "expediente": "715123",
      "carrera": "Ingeniería en Sistemas Computacionales",
      "email": "is715123@iteso.mx"
}


###

GET http://localhost:3000/api/users/2
x-auth-user: EU4Pn0k5lh-1
###

POST http://localhost:3000/api/login
Content-Type: application/json

{
    "email":"is715468@iteso.mx",
    "password": "soyRule"
}

###

POST http://localhost:3000/api/login
Content-Type: application/json

{
    "email":"is716122@iteso.mx",
    "password": "mduranp"
}


###

POST http://localhost:3000/api/login
Content-Type: application/json

{
    "email":"is715468@iteso.mx",
    "password": "soyRule"
}


###

GET http://localhost:3000/api/users
x-auth-user: EU4Pn0k5lh-1