POST http://localhost:3000/api/users
Content-Type: application/json

{
      "nombre": "Omar",
      "apellido": "Soto",
      "password": "elOmi",
      "expediente": "711111",
      "carrera": "Ingeniería en Sistemas Computacionales",
      "email": "ie711111@iteso.mx"
}

###

POST http://localhost:3000/api/users
Content-Type: application/json

{
      "nombre": "Anahí",
      "apellido": "Santana",
      "password": "aSantana",
      "expediente": "715123",
      "carrera": "Ingeniería en Sistemas Computacionales",
      "email": "is715123@iteso.mx"
}


###

GET http://localhost:3000/api/users

###

GET http://localhost:3000/api/num

###

POST http://localhost:3000/api/num
Content-Type: application/json

{
    "num":"5"
}





###

POST http://localhost:3000/api/login
Content-Type: application/json

{
    "email":"is715468@iteso.mx",
    "password":"soyRule"
}

###

GET http://localhost:3000/api/users
x-auth-user: thrlFkBRZu-1