
POST http://localhost:3000/api/users
Content-Type: application/json
x-auth-user: EU4Pn0k5lh-1

{
      "nombre": "Anahí",
      "apellido": "Santana",
      "password": "aSantana",
      "expediente": "715123",
      "carrera": "Ingeniería en Sistemas Computacionales",
      "email": "is715123@iteso.mx"
}


###

GET http://localhost:3000/api/users/1
x-auth-user: vv5bnxe68r-1
###

DELETE  http://localhost:3000/api/users/4
x-auth-user: vv5bnxe68r-1
###

POST http://localhost:3000/api/login
Content-Type: application/json

{
    "email":"is715468@iteso.mx",
    "password": "soyRule"
}

###

POST http://localhost:3000/api/login
Content-Type: application/json

{
    "email":"is715123@iteso.mx",
    "password": "aSantana"
}



###
GET http://localhost:3000/api/users
x-auth-user: Le140DmF5q-1


###

POST http://localhost:3000/api/profes
Content-Type: application/json
x-auth-user: Le140DmF5q-1

{
      "nombre": "Rodolfo Luthe",
      "departamento": "Electrónica, Sistemas e Informática",
      "añosExp": "1",
      "materias": [],
      "id": 1
    }

###

GET http://localhost:3000/api/profes


###

GET http://localhost:3000/api/profes?departamento=Electrónica, Sistemas e Informática





###

DELETE http://localhost:3000/api/profes/2

###
PUT http://localhost:3000/api/profes/1
Content-Type: application/json

{
      "nombre": "Oscar Luthe"
}


###-----  MATERIAS -----####
###
POST http://localhost:3000/api/Materias
Content-Type: application/json
x-auth-user: UGYQ1QmyNd-1

{
      "nombre": "Cerámica utilitaria",
      "descripción": "La cerámica es una de las tradiciones más arraigadas en la historia de la humanidad, México no es la excepción y en el país podemos encontrar una gran diversidad de trabajo con arcilla a lo largo de todo el territorio. ",
      "creditos": "8",
      "departamento": "Saberes Complementarios"
}

###
GET http://localhost:3000/api/Materias

###
GET http://localhost:3000/api/Materias/1

###
GET http://localhost:3000/api/Materias?nombre_like=os

###
GET http://localhost:3000/api/Materias?departamento=Ciencias

###
GET http://localhost:3000/api/Materias?nombre_like=os&departamento=Electrónica, Sistemas e Informática



########################### SUGERENCIAS #################################
###

POST http://localhost:3000/api/login
Content-Type: application/json

{
    "email":"is715123@iteso.mx",
    "password": "aSantana"
}

###

POST http://localhost:3000/api/login
Content-Type: application/json

{
    "email":"is715468@iteso.mx",
    "password": "soyRule"
}

###
GET  http://localhost:3000/api/sugerencias
x-auth-user: lm7Ow3nIda-3


###
DELETE  http://localhost:3000/api/sugerencias/2
x-auth-user: UPIqfGzO8g-1

########################### Detalle Materias #################################
###
POST http://localhost:3000/api/detalleMaterias
Content-Type: application/json
//x-auth-user: UGYQ1QmyNd-1

{
    "profesor": "Oscar Luthe",
    "materia": "Gestión de bases de datos",
    "numReviews": "0",
    "experiencia general": "0",
    "dificultad": "0",
    "preparación": "0",
    "carga trabajo": "0",
    "flexibilidad": "0",
    "ritmo": "0"
}